[database]
username = "root"
password = ""
hostname = "localhost"
port = "3306"
name = "crawlfish"
parameter = "?parseTime=true"

[server]
address = "0.0.0.0:8001"

[firebase]
url = "https://crawlfish-dev.firebaseio.com"
auth = "BM0t8EUKDonU7qOkBx0eipAmB6YKQtp5rRdcNuga"